# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28617f5ee310524bcb14ec2787e290ffcf5d119137c9cc6c942bc3e65c15c59f763dce7ce286ce598b5b22c5061e735136c9f3c7dc490fe79234e2509ba75cc2

test:
  secret_key_base: 880f2f570cceee8e3586ed3ea2af85e7c0516fe98a08c15c598f8cec54979b2dba70272a920bae44c611e00200363b9b15e79fdc3ed705ea3a79e51cd980645c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
